name: 👀 Markdown Lint Check

on: push

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Markdown Lint
        run: npm run lint
